alias cl='clear'
alias cdd='cd ~/dotfiles'
alias gitpush='git add . && git commit -m "without comment" && git push'
alias ll='ls -al'
alias ls='ls -a'
alias notes='nvim ~/Nextcloud/Notes/Privat/Quicknotes.md'
alias update='sudo apt update && sudo apt upgrade && flatpak update && sudo snap refresh'
